// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ljsLiP7Teo6NYIylar0_LYazRzeoCpg',
    appId: '1:1069540851368:web:fd4584f76fb40ff6a78c9d',
    messagingSenderId: '1069540851368',
    projectId: 'supapay-d5baf',
    authDomain: 'supapay-d5baf.firebaseapp.com',
    storageBucket: 'supapay-d5baf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPw7zu9D_BJrJD-YLgncJkGNMvm2aV740',
    appId: '1:1069540851368:android:525bce21d53ef1caa78c9d',
    messagingSenderId: '1069540851368',
    projectId: 'supapay-d5baf',
    storageBucket: 'supapay-d5baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtO9GDie8jSrmTmnNnFAa-U1KjXqHUxo',
    appId: '1:1069540851368:ios:18c246a8e184fdf6a78c9d',
    messagingSenderId: '1069540851368',
    projectId: 'supapay-d5baf',
    storageBucket: 'supapay-d5baf.appspot.com',
    iosBundleId: 'com.example.supapay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtO9GDie8jSrmTmnNnFAa-U1KjXqHUxo',
    appId: '1:1069540851368:ios:18c246a8e184fdf6a78c9d',
    messagingSenderId: '1069540851368',
    projectId: 'supapay-d5baf',
    storageBucket: 'supapay-d5baf.appspot.com',
    iosBundleId: 'com.example.supapay',
  );
}
